// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function Connect(arg1:string):Promise<void>;

export function CreateConnection(arg1:models.Connection):Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function GetConnection(arg1:string):Promise<models.Connection>;

export function GetSettings():Promise<models.Settings>;

export function Greet(arg1:string):Promise<string>;

export function IsConnected(arg1:string):Promise<boolean>;

export function ListConnections():Promise<Array<models.Connection>>;

export function Publish(arg1:main.PublishInput):Promise<void>;

export function Subscribe(arg1:main.SubscribeInput):Promise<void>;

export function Unsubscribe(arg1:main.UnsubscribeInput):Promise<void>;

export function UpdateConnection(arg1:models.Connection):Promise<void>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;
