// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function CreateSubscription(arg1) {
  return window['go']['main']['App']['CreateSubscription'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteMessagesByConnection(arg1) {
  return window['go']['main']['App']['DeleteMessagesByConnection'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function ExportAll() {
  return window['go']['main']['App']['ExportAll']();
}

export function GetAllConnectionStats() {
  return window['go']['main']['App']['GetAllConnectionStats']();
}

export function GetConnection(arg1) {
  return window['go']['main']['App']['GetConnection'](arg1);
}

export function GetConnectionStats(arg1) {
  return window['go']['main']['App']['GetConnectionStats'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportAll(arg1) {
  return window['go']['main']['App']['ImportAll'](arg1);
}

export function IsConnected(arg1) {
  return window['go']['main']['App']['IsConnected'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListMessages(arg1) {
  return window['go']['main']['App']['ListMessages'](arg1);
}

export function ListPublishHeaders(arg1) {
  return window['go']['main']['App']['ListPublishHeaders'](arg1);
}

export function ListPublishPayloads(arg1) {
  return window['go']['main']['App']['ListPublishPayloads'](arg1);
}

export function ListSubscriptions(arg1) {
  return window['go']['main']['App']['ListSubscriptions'](arg1);
}

export function Publish(arg1) {
  return window['go']['main']['App']['Publish'](arg1);
}

export function Subscribe(arg1) {
  return window['go']['main']['App']['Subscribe'](arg1);
}

export function Unsubscribe(arg1) {
  return window['go']['main']['App']['Unsubscribe'](arg1);
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateSubscription(arg1) {
  return window['go']['main']['App']['UpdateSubscription'](arg1);
}
