// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateConnection(arg1) {
  return window['go']['main']['App']['CreateConnection'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function GetConnection(arg1) {
  return window['go']['main']['App']['GetConnection'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function UpdateConnection(arg1) {
  return window['go']['main']['App']['UpdateConnection'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
